name: CI

on:
  push:
    branches: [master]
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-20.04
    container: golang:1.18.1
    steps:
    - uses: actions/checkout@v1
    - name: Run Tests
      run: make test
    - name: Build
      run: make build
  lint:
    runs-on: ubuntu-20.04
    container: golangci/golangci-lint:v1.45.2
    steps:
    - uses: actions/checkout@v1
    - name: Run Linters
      run: make lint
