name: release

on:
  push:
    tags:
      - v*

jobs:
  goreleaser:
    runs-on: ubuntu-20.04
    container: golang:1.18.1
    steps:
    - uses: actions/checkout@v1
    - name: Run Tests
      run: make test
    - name: Go Tidy
      run: make tidy
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        distribution: goreleaser
        version: v1.8.3
        args: release --config=build/package/.goreleaser.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
